### ISSUE TITLE
Synchronization questions

### ISSUE THREAD

**Issue by erikvullings** [enmasseio/hypertimer#2]
When synchronizing between master and slaves, is it possible for:
1. A slave to indicate that he is ready, i.e. the master should not increment the time until all slaves are done with their current step. Otherwise, one slave may start to lag behind.
2. A slave to indicate when he needs a new time event, so the triggers or timeouts that he sets are transmitted to the master, and the master will generate a time event as requested. 
3. The master to pause time or change the simulation speed, and this will update the planned triggers. For example, if I've planned a trigger in 10s time, and the speed factor changed from 1 to 2, I expect the event in 5s. And when I pause time, the event should not occur until I continue again.

**Comment by josdejong** [comment]
I think you're referring to synchronizing non-paced simulation time. I would love to implement this, it's is still missing in the implementation, and it's crucial in order to be able to scale simulations. 

From the docs on Synchronization:

> WARNING: this is an experimental feature, and currently only supports _paced_ mode.

https://github.com/enmasseio/hypertimer#synchronization

**Comment by erikvullings** [comment]
Thanks for the reply, but actually, question 1 and 3 were aimed at paced mode. 

In 1, if the master increases the time every second, and a slave is not ready processing the last time step, how can the slave tell the master to wait a bit?

For 3, when the slave has set some triggers or timeouts, how are they affected when the master pauses or changes the speed?

**Comment by josdejong** [comment]
Sorry for the late reply.

This is an interesting point. In paced (continuous or "animated") mode, would you expect/want a distributed system to just continue in parallel and ignore the duration of actions themselves? Or do you still want everything to run in `deterministic` order? If one event takes place at t=0s and execution takes 2s, and another event takes place at t=1s, should this event wait for the first to be finished and thus start 1s too late?

I think what you are looking for is a paced _and_ deterministic mode? The experimental support for synchronization doesn't do things in a deterministic order. And I'm personally most interested in a non-paced + deterministic mode :).
