### ISSUE TITLE
`ws@0.8.1` is vulnerable and fails `nsp check`

### ISSUE THREAD

**Issue by HiFaraz** [enmasseio/hypertimer#6]
Running `nsp check` on `hypertimer@2.1.3` (latest version published to npm) shows that `ws@0.8.1` has a few security advisories against it:

https://nodesecurity.io/advisories/67 (Remote Memory Disclosure)
https://nodesecurity.io/advisories/120 (DoS due to excessively large websocket message)
https://nodesecurity.io/advisories/550 (Denial of Service)

All vulnerabilities are patched from versions `>=3.3.1`

Could you please upgrade your `ws` dependency?

**Comment by josdejong** [comment]
Thanks for reporting @HiFaraz , I will update the dependencies soon.

**Comment by josdejong** [comment]
Both #6 and #7 should be fixed in v3.0.0. @HiFaraz would be great if you could check whether v3.0.0 works for you.

**Comment by HiFaraz** [comment]
Apologies for the late response. I don't see the issue now. Thanks!!!

**Comment by josdejong** [comment]
:+1:
