### ISSUE TITLE
`debug@2.2.0` is vulnerable and fails `nsp check`

### ISSUE THREAD

**Issue by HiFaraz** [enmasseio/hypertimer#7]
Running `nsp check` on `hypertimer@2.1.3` (latest version published to npm) shows that `debug@2.2.0` has a security advisory against it:

https://nodesecurity.io/advisories/534 (Regular Expression Denial of Service)

All vulnerabilities are patched from versions `>=3.1.0`

Could you please upgrade your `debug` dependency?

**Comment by josdejong** [comment]
Both #6 and #7 should be fixed in v3.0.0. @HiFaraz would be great if you could check whether v3.0.0 works for you.
